server:
  port: 2525
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
            
  mail:
            host: smtp.gmail.com
            port: 587
            username: jagadeepbarik@gmail.com
            password: *****
            
            
            
            properties:
                    mail:
                        smtp:
                              auth: true
                              connectiontimeout: 5000
                              timeout: 5000
                              writetimeout: 5000
   
             
                              starttls:
                                  enable: true
       
